# Generated by Django 4.0.1 on 2022-01-31 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=100)),
                ('lname', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('email', models.EmailField(default='', max_length=200)),
                ('companyName', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('securityQuestion', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('securityAnswer', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('password', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('pin', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('token', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('status', models.CharField(default='0', max_length=10)),
                ('addedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('modifyDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
