# Generated by Django 4.0.1 on 2022-01-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_passwordhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(max_length=100)),
                ('macId', models.CharField(max_length=100)),
                ('deviceId', models.CharField(max_length=10)),
                ('userId', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
